version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
    restart: unless-stopped
